production:
  clients:
    default:
      database: <%= ENV['DB_NAME'] %>
      hosts:
        - <%= ENV['DB_HOST'] %>
      options:
        user: <%= ENV['DB_USER'] %>
        password: <%= ENV['DB_PASS'] %>
        auth_source: admin
        ssl: false

development:
  # Configure available database clients. (required)
  clients:
    # Defines the default client. (required)
    default:
      database: <%= ENV['DB_NAME'] %>
      hosts:
        - <%= ENV['DB_HOST'] %>
      options:

  # Configure Mongoid specific options. (optional)
  options:

test:
  clients:
    default:
      database: huanlv_test
      hosts:
        - localhost:27017
      options:
        read:
          mode: :primary
        max_pool_size: 1
